### ISSUE TITLE
How to change size for thumbnail

### ISSUE THREAD

**Issue by alejofonseca** [2amigos/yii2-file-upload-widget#144]
Hi @tonydspaniard,

A quick question: how to change the thumbnail size? It currently gives me something like the attached image.
![ibbux](https://user-images.githubusercontent.com/1123549/39715236-40765ba6-51f2-11e8-900b-9fd8eda2a01f.png)

Thank you.

**Comment by moneyadmin** [comment]
Use `preview*` https://github.com/blueimp/jQuery-File-Upload/wiki/Options#previewmaxheight

Example:
`    
//...
'clientOptions' => [
//...
        'previewMaxWidth' => 100,
    ],
//...
`

**Comment by Tolembek** [comment]
How to upload the size of the picture (before updating the page)?

**Comment by Tolembek** [comment]
'previewMaxWidth' => 100 does not work

**Comment by Tolembek** [comment]
help me

**Comment by alejofonseca** [comment]
I am sorry mate, I used a different system for uploads. This one does not have proper documentation, so... it sacks.

**Comment by tonydspaniard** [comment]
@alejofonseca @Tolembek I would simply use `CSS`: https://github.com/2amigos/yii2-file-upload-widget/blob/master/src/views/upload.php#L6. The views have classes that you can manipulate with CSS. 

@alejofonseca instead of complaining about not having proper documentation. Why don't you help us to improve it by providing a PR? What really `SUCKS`, apart of your english skills, is that you don't have any empathy at all for those who give away their precious time to help people by submitting libraries. People like you make open source work a terrible place to be and one of the reasons I moved away for so long.
