### ISSUE TITLE
Doesn't work in a Modal

### ISSUE THREAD

**Issue by glitch1337** [2amigos/yii2-file-upload-widget#15]
I am loading a form into a modal via AJAX and the widget renders all buttons and the browse button functions, however the gallery doesn't populate when you select a file.

Any help?

**Comment by tonydspaniard** [comment]
If you are working with AJAX you are required to process the javascript files somehow. I highly recommend you that instead of processing the js files each time the modal opens, you trigger the  initialization of the plugin through your own javascript code. 

This is not an issue of the plugin, but an issue of the approach used to make it work.
