### ISSUE TITLE
Unable to verify your data submission

### ISSUE THREAD

**Issue by KUbo0** [2amigos/yii2-file-upload-widget#59]
I have such a problem for a long time, it appears suddenly as disappears.
better I could do it turn to false enableCsrfValidation in controller beforeAction.
I tried to add clientOption `'formData' => ['_csrf'=>new JsExpression('yii.getCsrfToken()')]` also unpredictable.
seems it global Ajax app issue, but I have checked everything many times..

**Comment by tonydspaniard** [comment]
can you provide some code?

**Comment by KUbo0** [comment]
Since my comment by process of elimination I've created [purge template](https://github.com/KUbo0/yii2-csrf-fail). It seems global csrf stuck.
Was obliged to move my project from the beginning.
There is no your mistake, but if you or @nenad-zivkovic can suggest my - I'll be grateful !!

**Comment by nenad-zivkovic** [comment]
Where is the code that fails. What you was trying to do and how ?

**Comment by KUbo0** [comment]
Excuse me, I forgot to add the link (
https://github.com/KUbo0/yii2-csrf-fail

**Comment by nenad-zivkovic** [comment]
I still can not find YOUR code that is causing problem. I am not using this widget and do not know how to help you if you do not show me your code. All I see here is template code.

Also, can you please try whatever you was doing on https://github.com/nenad-zivkovic/yii2-basic-template , because if you was using `@uploads` alias the issue may be fixed in 2.3.0 version.

**Comment by tonydspaniard** [comment]
I am currently using the widget in many of it's forms and do not have the issue you're talking about. I think this is not caused by the widget but with the knowledge regarding Yii2 and how to handle uploads.

Also, there is no information whatsoever on the issue itself (code) so I am closing this issue.

**Comment by MuhammedSami** [comment]
Hello dear 2amigos develloper, 
I'm using your file-upload widget for my yii2 project, but I get the following error: 'Unable to verify your data submission'
When I upload the file, in the network tab there is no csrf token sent within post request 
How can handle this issue ?
